# Generated by Django 3.2.4 on 2021-06-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0003_appoinment_priorty'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('mail', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('priorty', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
        ),
    ]
